maketex: exit then $1 and $1.tex don't exist

diff --git a/scripts/.local/bin/maketex b/scripts/.local/bin/maketex
--- a/scripts/.local/bin/maketex
+++ b/scripts/.local/bin/maketex
@@ -19,8 +19,13 @@ tmpdir="/tmp/$(basename $(dirname $(realpath $1)))"
 
 tex_command="latexmk -pdf -synctex=1 -interaction=nonstopmode -output-directory=$tmpdir -aux-directory=$tmpdir"
 
-if [ -f "$1".tex ] && [ ! -f "$1" ]; then
-	$0 "$1".tex
+if [ ! -f "$1" ]; then
+	if [ -f "$1".tex ]; then
+		$0 "$1".tex
+	else
+		echo "File $1 or $1.tex not found"
+		exit 1
+	fi
 fi
 
 if [ -f "$1" ]; then
